apiVersion: v2
appVersion: "1.0.0"
description: A Helm chart that sets up the Kubecost Cloud agent with Prometheus to monitor Kubernetes costs.
name: kubecost-cloud-agent
version: "1.0.4"
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
dependencies:
  - condition: global.prometheus.enabled
    name: prometheus
    repository: file://./dependencies/prometheus
    version: "~11.0.2"
