{{- if .Values.cloudAgent }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cloudAgentTLSCertName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  cloud-cert.pem:  {{ .Files.Get .Values.cloudAgentTLSFileName | b64enc }}
{{- end }}